repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    - id: black
      language_version: python3

  - repo: https://github.com/keewis/blackdoc
    rev: v0.3.9
    hooks:
    - id: blackdoc
      additional_dependencies: ["black[jupyter]"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
    - id: mypy
      exclude: tests

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    - id: codespell
      types_or: [python, markdown]
      additional_dependencies: [tomli]

  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3
    hooks:
    -   id: lintr
        args: [--warn_only, --key=value]
        verbose: true
    -   id: style-files
        args: [--scope=spaces, --reindention=specify_reindention('#')]
    -   id: no-browser-statement
    -   id: no-print-statement
    -   id: no-debug-statement
    -   id: spell-check
